Zorbus\GlossaryBundle\Entity\Entry:
    type: entity
    table: zorbus_glossary_entry
    repositoryClass: Zorbus\GlossaryBundle\Entity\EntryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        letter:
            type: string
            length: 1
            nullable: false
        expression:
            type: string
            length: 255
            nullable: false
        definition:
            type: text
            nullable: false
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    separator: '-'
                    style: default
                    fields:
                        - expression
        enabled:
            type: boolean
            default: true
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        glossary:
            targetEntity: Zorbus\GlossaryBundle\Entity\Glossary
            inversedBy: entries
            joinColumn:
                name: glossary_id
                referencedColumnName: id
                onDelete: CASCADE