Zorbus\GlossaryBundle\Entity\Glossary:
    type: entity
    table: zorbus_glossary_glossary
    repositoryClass: Zorbus\GlossaryBundle\Entity\GlossaryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        identifier:
            type: string
            length: 255
            nullable: false
        letters:
            type: string
            length: 255
            nullable: false
        title:
            type: string
            length: 255
            nullable: false
        description:
            type: text
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    separator: '-'
                    style: default
                    fields:
                        - title
        enabled:
            type: boolean
            default: true
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    oneToMany:
        entries:
            targetEntity: Zorbus\GlossaryBundle\Entity\Entry
            mappedBy: glossary
            orderBy:
                expression: ASC