<?php

namespace Zorbus\GlossaryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlossaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlossaryRepository extends EntityRepository
{
}
